# .github/workflows/android_build.yml

name: Android APK Build

on:
  push:
    branches:
      - main # Asegúrate de que esta sea tu rama principal (en tu caso, 'main')
  pull_request:
    branches:
      - main # Asegúrate de que esta sea tu rama principal (en tu caso, 'main')

jobs:
  build:
    runs-on: ubuntu-latest # Usamos un entorno Linux (Ubuntu)

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Descarga tu código del repositorio

    - name: Set up Java Development Kit (JDK)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # Distribución de OpenJDK
        java-version: '17' # Versión de Java requerida para Android

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # Usamos una versión estable de Python
      id: setup-python # Le damos un ID para acceder a su salida

    - name: Install Buildozer dependencies
      run: |
        sudo apt-get update
        # Añadido automake para complementar autoconf y libtool
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses-dev libffi-dev libssl-dev build-essential automake
      # Estas son las dependencias necesarias para Buildozer en Ubuntu

    - name: Upgrade pip and wheel
      run: |
        python3 -m pip install --upgrade pip wheel

    - name: Install Buildozer
      run: |
        # Usar python3 -m pip para asegurar que se use la instalación de Python correcta
        # Instalar buildozer, cython y setuptools explícitamente
        python3 -m pip install buildozer cython setuptools

    - name: Remove Buildozer Cache # Elimina la caché de Buildozer para asegurar una compilación limpia.
      run: |
        echo "Eliminando caché de Buildozer para asegurar una compilación limpia..."
        rm -rf .buildozer
      # Esto previene que archivos residuales de compilaciones anteriores causen problemas.

    - name: Install Android SDK Build-Tools via SDK Manager # <--- ¡NUEVO PASO CRÍTICO!
      run: |
        # Configurar ANDROID_HOME y ANDROID_SDK_ROOT para sdkmanager
        echo "ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
        mkdir -p $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin
        # Descargar sdkmanager
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-8583971_latest.zip -O /tmp/cmdline-tools.zip
        unzip -q /tmp/cmdline-tools.zip -d $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest
        # Añadir sdkmanager al PATH
        echo "$HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH

        # Aceptar licencias del SDK de Android
        yes | $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

        # Instalar la versión de Build-Tools necesaria (ej. 33.0.0)
        echo "Instalando Android SDK Build-Tools 33.0.0..."
        $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager "build-tools;33.0.0" "platform-tools" "platforms;android-33"

    - name: Update Android SDK with Buildozer
      run: |
        # Configuración de entorno Python para este paso
        PYTHON_BIN="${{ steps.setup-python.outputs.pythonLocation }}/bin/python3"
        sudo ln -sf "$PYTHON_BIN" /usr/local/bin/python || true
        export PYTHON="$PYTHON_BIN"
        echo "Actualizando SDK de Android con Buildozer (verificación adicional)..."
        # Este comando ahora debería encontrar las herramientas ya instaladas por sdkmanager
        python -m buildozer android update
      # Este paso asegura que el SDK esté instalado y las licencias aceptadas.

    - name: Build Android APK
      run: |
        # Añadido 'set -e' para que el workflow falle inmediatamente si un comando falla.
        set -e
        # Configuración de entorno Python para este paso
        PYTHON_BIN="${{ steps.setup-python.outputs.pythonLocation }}/bin/python3"
        sudo ln -sf "$PYTHON_BIN" /usr/local/bin/python || true
        export PYTHON="$PYTHON_BIN"
        echo "Iniciando compilación del APK..."
        # Ejecutar Buildozer para compilar el APK.
        python -m buildozer android debug
      # Este comando iniciará la compilación del APK.

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: NeuroLinkApp-APK
        path: bin/*.apk
      # Sube el APK generado para que puedas descargarlo.
      # El APK estará en la carpeta 'bin' de tu proyecto.
