# .github/workflows/android_build.yml

name: Android APK Build

on:
  push:
    branches:
      - main # Asegúrate de que esta sea tu rama principal (en tu caso, 'main')
  pull_request:
    branches:
      - main # Asegúrate de que esta sea tu rama principal (en tu caso, 'main')

jobs:
  build:
    runs-on: ubuntu-latest # Usamos un entorno Linux (Ubuntu)

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Descarga tu código del repositorio

    - name: Set up Java Development Kait (JDK)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # Distribución de OpenJDK
        java-version: '17' # Versión de Java requerida para Android

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # Usamos una versión estable de Python
      id: setup-python # Le damos un ID para acceder a su salida

    - name: Install Buildozer dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses-dev libffi-dev libssl-dev build-essential
      # Estas son las dependencias necesarias para Buildozer en Ubuntu

    - name: Install Buildozer
      run: |
        # Usar python3 -m pip para asegurar que se use la instalación de Python correcta
        python3 -m pip install buildozer

    - name: Build Android APK
      run: |
        # Obtener la ruta exacta del directorio binario de Python instalado por setup-python
        PYTHON_BIN_DIR="${{ steps.setup-python.outputs.pythonLocation }}/bin"
        echo "Añadiendo $PYTHON_BIN_DIR a PATH para Buildozer."
        # Añadir el directorio de Python al PATH para que Buildozer encuentre 'python'
        export PATH="$PYTHON_BIN_DIR:$PATH"

        # Exportar la variable de entorno PYTHON para asegurar que Buildozer la encuentre.
        # Aunque el PATH es más robusto, esta variable puede ser un respaldo.
        export PYTHON="$PYTHON_BIN_DIR/python3"

        # Ejecutar Buildozer. Ahora debería encontrar 'python' en el PATH.
        buildozer android debug
      # Este comando iniciará la compilación del APK.
      # La primera vez descargará el SDK/NDK, lo que puede tardar.

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: NeuroLinkApp-APK
        path: bin/*.apk
      # Sube el APK generado para que puedas descargarlo.
      # El APK estará en la carpeta 'bin' de tu proyecto.
